### ISSUE TITLE
Could not find robopods-appodeal-ios

### ISSUE THREAD

**Issue by balepc** [MobiDevelop/robovm-robopods#47]
Trying to integrate Appodeal for iOS game. 

But this doesn't seems to be working
`compile "org.robovm:robopods-appodeal-ios:$robopodsVersion"`

**Comment by alex-dorokhov** [comment]
It seems to be that Appodeal Robopod is not yet deployed to Maven Central. 

Try to use 2.2.2-SNAPSHOT version of robopods, or clone the repo and run from command line:
```
cd robovm-robopods
mvn3 install
```

**Comment by Tom-Ski** [comment]
snapshots been pushed, you'll find it in the https://oss.sonatype.org/content/repositories/snapshots repository

**Comment by balepc** [comment]
Cannot find it. Should it be here - https://oss.sonatype.org/content/repositories/snapshots/org/robovm/ ??

**Comment by alex-dorokhov** [comment]
Since original RoboVM project was closed, the package name of artifacts was changed from **org.robovm** to **com.mobidevelop** .
The Appodeal robopod is here: https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/
If you use gradle, then you just have to add the snapshot repo into the list of repos. Like this:
```
repositories {
        ...
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

ext.robopodsVersion="2.2.2-SNAPSHOT"

dependencies {
      ...
      compile "com.mobidevelop.robovm:robopods-appodeal-ios:${robopodsVersion}"
}
```

**Comment by balepc** [comment]
Thanks! It worked!
